name: Echo release version

on:
  release:
    types: [published]

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Set release version
      
    - name: Display release version
      env:
        RELEASE_VERSION: ${GITHUB_REF#refs/*/}
      run: echo $RELEASE_VERSION
    
